name: Run Stock Codes

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  run_stock_codes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openai requests  # If you have any dependencies

    - name: Run Stock Codes script
      run: python Stock_Codes.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
