name: Run Stock Codes

on:
  workflow_dispatch: 

jobs:
  run_stock_codes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests bs4 beautifulsoup4  # If you have any dependencies

    - name: Run Stock Codes script
      run: python Holdings.py

    - name: Create or update CSV files
      run: |
          # Assuming CSV files are in the same directory
          for file in *.csv; do
            [ -e "$file" ] || continue
            echo "Processing $file"
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git add "$file"
            git commit -m "Automated commit - $file" || true
          done
          git push
