name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Run Symbols.py
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
        run: |
          python Symbols.py  # Replace 'path/to/Symbols.py' with the actual path
